### ISSUE TITLE
Custom Logos

### ISSUE THREAD

**Issue by psychemedia** [dunovank/jupyter-themes#129]
Is there a theme that demonstrates how to add a custom logo?

**Comment by dunovank** [comment]
Here's a hack for adding a custom logo in the css:

1. Create an `images` folder in the `notebook` styles directory and save a copy over your logo 
image (`logo.png`)

```python
import os
import notebook
from shutil import copyfile

# change path to wherever your logo is stored
logo_png_src = '/path/to/logo.png' 

conda_notebook_dir =  os.sep.join(notebook.__file__.split(os.sep)[:-1]) 
notebook_images_dir = os.path.join(conda_notebook_dir, 'static/style/images')
if not os.path.isdir(notebook_images_dir):
        os.makedirs(notebook_images_dir)

logo_png_notebook = os.path.join(notebook_images_dir, 'logo.png')
copyfile(logo_png_src, logo_png_notebook)
```

2. Then in your ~/.jupyter/custom/custom.css:
```css
body, div.body {
    background: url("images/logo.png") no-repeat;
    background-size: 138px;
    background-position-y: 13px;
    background-position-x: 13px;
}

.notebook_app #header, .edit_app #header {
    box-shadow: none !important;
    background: url("images/logo.png") no-repeat;
    background-size: 138px;
    background-position-y: 13px;
    background-position-x: 13px;
}
```

(willl probably have to play around with the background-size and x,y values depending on the size/shape of your logo)
