### ISSUE TITLE
pdb cells rendering off-white text on white background

### ISSUE THREAD

**Issue by dhitals** [dunovank/jupyter-themes#136]
I am using 'ocean-dark' theme. In the `pdb` cells, off-white text is rendered on white background, making it unreadable.  Which `div` needs to changed for that? I looked into the custom css files as well as the default css file for Jupyter notebook but could not figure it out. 

Thanks!

**Comment by dunovank** [comment]
I assume you're using the oceans16 theme right? There's no theme named ocean-dark what version are you running? browser? I just checked and pdb is rendering fine for me.

**Comment by dhitals** [comment]
Sorry for the delay, Kyle.

Ocean16 Dark theme. Python 3. On Safari/Firefox/Chrome.

How does your pdb (or ipdb) render? In my notebook code cells are dark but pdb cells are white. The text on those cells is off-white, so I can read them but barely. It would be great to change one of those colors.

I have been using your theme for over a year, so it could be an older version. I made some of my own changes to the CSS, so am hesitant to switch right away.

**Comment by dunovank** [comment]
yeah I fixed the pdb issue a while back so an update probably fix it. Try this: backup any customized code youve added to your custom.css file, copy/paste the code below into `</path/to/your/site-packages/directory>/jupyterthemes/layout/extras.less` file, then reinstall a theme using `jt -t <themename>`, copy any custom css code back over into the new custom.css file that gets created.

```less
/********** DEBUGGER PATCH **********/
input.raw_input {
    font-family: monospace;
    font-size: @monofontsize !important;
    color: @cc-input-fg;
    background-color: @codeblock-bg;
    border-color: darken(@codeblock-bg, 1%);
    background: darken(@codeblock-bg, 1%);
    width: auto;
    vertical-align: baseline;
    padding: 0em 0.25em;
    margin: 0em 0.25em;
    -webkit-box-shadow: none;
    box-shadow: none;
}
```
if you get an error trying to install the theme, you might just try replacing `@codeblock-bg` and `@cc-input-fg` variables with #hex colors that make sense.

Hope that helps!
