### ISSUE TITLE
Border not left alignment between markdown and code cells.

### ISSUE THREAD

**Issue by Peydon** [dunovank/jupyter-themes#210]
![default](https://user-images.githubusercontent.com/22172378/34105874-f9f94bae-e430-11e7-8fe1-f27874f10a76.png)

**Comment by joilus** [comment]
Same problem here

**Comment by medicm** [comment]
Managed to temporary fix this untill it gets fixed correctly by playing around with some numbers and changing div.prompt.input_prompt in cells.less in jupyterthemes/layout by removing 2 lines and adding 2 lines
```css 
div.prompt.input_prompt {
    .
    .
    .
    /*
    min-width: @prompt-min-width;
    width: @prompt-min-width !important;

    if these numbers don't work for you just play around with them, 
    and make sure you re-apply the theme after every change
    */
    min-width: 11.7ex !important;
    max-width: 11.7ex;
}
``` 
and by adding `padding-right: 10px;` in a block in codemirror.less to fix the line numbers in markdown edit mode
 ```css
.CodeMirror-linenumber,
div.CodeMirror-linenumber,
.CodeMirror-gutter.CodeMirror-linenumber
div.CodeMirror-gutter.CodeMirror-linenumber {
    .
    .
    .
    padding-right: 10px;
}
```

after saving, just re-apply the theme with `jt -t`
![capture](https://user-images.githubusercontent.com/15942498/34541783-e68aaf1c-f0d9-11e7-8153-d8ea26f50ce8.PNG)
