### ISSUE TITLE
Title name hardly visible

### ISSUE THREAD

**Issue by 907386253** [dunovank/jupyter-themes#219]
When I change the Jupyter theme to gruvboxd( and other dark themes) with the codes:
jt -t gruvboxd -T -N
 the color of the title is still black, which makes it nearly impossible for me to see.
Are there any solutions? Such as changing the color of the title?
Thanks a lot.
<img width="758" alt="question" src="https://user-images.githubusercontent.com/35222346/34703667-24c32594-f52f-11e7-8ac5-8525281534b1.PNG">

**Comment by laitnesserof** [comment]
Go to ```~/.jupyter/custom/custom.css``` and change 'span.save_widget span.filename' and 'span.save_widget span.filename:hover'.

Here is my personal setting:
```css
span.save_widget span.filename {
 margin-left: 8px;
 font-size: 120%;
 color: #ae81ff;
}
span.save_widget span.filename:hover {
 color: #ae81ff;
 text-shadow: 0 0 5px #ae81ff;
 background-color: transparent;
}
```
