### ISSUE TITLE
[feature request] Change color for focused cell

### ISSUE THREAD

**Issue by yech1990** [dunovank/jupyter-themes#275]
It is import for distinguishing cell, especially in vim mode!

```css
/**********************************
 customized by yech1990 for vim
**********************************/
/* Jupyter cell is in normal mode when code mirror */
.edit_mode .cell.selected .CodeMirror-focused.cm-fat-cursor {
  background-color: #002B36 !important;
}
/* Jupyter cell is in insert mode when code mirror */
.edit_mode .cell.selected .CodeMirror-focused:not(.cm-fat-cursor) {
  background-color: #211F20 !important;
}
```
