### ISSUE TITLE
Regaining Logo Fix Submission

### ISSUE THREAD

**Issue by MarkMoretto** [dunovank/jupyter-themes#389]
Hi,

Great repo! Thanks for putting it together.

I'm not sure if this is the intention, but after passing all the command line options for what I thought would include the Jupyter logo at the top right of a default notebook, nothing worked.  I ended up going into the custom.css file in my .jupyter folder and adjusting one small thing.

Previous:

```css
div#ipython_notebook {
    display: none;
}
```

New:

```css
div#ipython_notebook {
 display: block;
 height: 40px !important;
}
```

That's about it.  I think it's line ~817 in my generated `.css` file, but it also might be different in your [notebook.less](https://github.com/dunovank/jupyter-themes/blob/master/jupyterthemes/layout/notebook.less) file.

Now I'm back in business:

![image](https://user-images.githubusercontent.com/25012707/80660904-178d1380-8a5b-11ea-8166-994f94dd5089.png)

I'm on WIndows 10, Python 3.7.4, and the latest notebook version.

Thanks!
