### ISSUE TITLE
Conflicting with Vim Binding nbextentions

### ISSUE THREAD

**Issue by alextfkd** [dunovank/jupyter-themes#41]
I've found some conflicting issues with VIM Binding nbextensions.
VIM Binding extension also changes Jupyter CSS and therefore it's difficult to read text in the selected cells.
By changing two background colors in VIM Binding CSS as shown 

```css
/* ~/Library/Jupyter/nbextensions/vim_binding/vim_binding.css */
.CodeMirror-dialog-bottom {
  position: absolute;
  width: 100%;
  bottom: 0;
  z-index: 100;
  color: #eee;
  background-color: #333;
}
.CodeMirror-dialog-bottom input {
  border: none;
  outline: none;
  color: inherit;
  background-color: inherit;
  width: calc(100% - 1em);
}
/* Jupyter cell is in normal mode when code mirror */
.edit_mode .cell.selected .CodeMirror-focused.cm-fat-cursor {
  /* background-color: #F5F6EB; DEFAULT */
  background-color: #293340; /* MODIFIED for chesterish*/
}
/* Jupyter cell is in insert mode when code mirror */
.edit_mode .cell.selected .CodeMirror-focused:not(.cm-fat-cursor) {
  /* background-color: #F6EBF1; DEFAULT */
  background-color: #293340; /* MODIFIED for chesterish */
}
```

could improve code readability. (This change is for chesterish, for example.)
Anyway, thanks for this great theme-changer!

- before

![before](https://cloud.githubusercontent.com/assets/13083941/17462822/9b9710b6-5cf3-11e6-8bc8-ced57ff83189.png)

- after
![after](https://cloud.githubusercontent.com/assets/13083941/17462821/9591cf94-5cf3-11e6-844d-a13c87ca0c87.png)
